  float genweight,genM,genpT,pt_top1,pt_top2;
  float passEle27, passEle32, passEle35, passEle24Tau30;
  float matchEle27_1, matchEle32_1, matchEle35_1, matchEle24Tau30_1, matchEle24Tau30_2;
  float filterEle27_1, filterEle32_1, filterEle35_1, filterEle24Tau30_1, filterEle24Tau30_2;
  float photonIso_2, puIso_2, chargedIso_2, neutralIso_2,metcor,metcorphi;
  float byCombinedIsolationDeltaBetaCorrRaw3Hits_2, byIsolationMVA3oldDMwLTraw_2;
  float pt_1,pt_2,px_1,px_2,py_1,py_2,pz_1,pz_2,eta_1,eta_2,phi_1,phi_2,iso_1,e_1,e_2,m_1,m_2,isoDB_1; 
  float flag_BadChargedCandidate, flag_BadPFMuon, flag_EcalDeadCellTriggerPrimitive, flag_HBHENoise, flag_HBHENoiseIso, flag_badCloneMuon, flag_badGlobalMuon, flag_eeBadSc, flag_globalTightHalo2016, flag_goodVertices, flag_globalSuperTightHalo2016, flag_badMuons, flag_duplicateMuons, flag_ecalBadCalib;
  int gen_match_1, gen_match_2;
  int nbtag, nbtagWoNoisyJets;
  float numGenJets;
  int run, lumi, evt;
  float met_UESUp, met_UESDown, metphi_UESUp, metphi_UESDown;
  float Rivet_stage1_cat_pTjet30GeV,Rivet_stage0_cat, Rivet_higgsPt, Rivet_nJets30;
  int nup,njets,njetsWoNoisyJets;
  int njetsWoNoisyJets_JetEta0to3Up, njetsWoNoisyJets_JetEta0to5Up, njetsWoNoisyJets_JetRelativeSampleUp, njetsWoNoisyJets_JetRelativeBalUp, njetsWoNoisyJets_JetEta3to5Up, njetsWoNoisyJets_JetEta0to3Down, njetsWoNoisyJets_JetEta0to5Down, njetsWoNoisyJets_JetRelativeSampleDown, njetsWoNoisyJets_JetRelativeBalDown, njetsWoNoisyJets_JetEta3to5Down;
  float mjjWoNoisyJets_JetEta0to3Up, mjjWoNoisyJets_JetEta0to5Up, mjjWoNoisyJets_JetRelativeSampleUp, mjjWoNoisyJets_JetRelativeBalUp, mjjWoNoisyJets_JetEta3to5Up, mjjWoNoisyJets_JetEta0to3Down, mjjWoNoisyJets_JetEta0to5Down, mjjWoNoisyJets_JetRelativeSampleDown, mjjWoNoisyJets_JetRelativeBalDown, mjjWoNoisyJets_JetEta3to5Down;
  float m_sv, m_sv_UP, m_sv_DOWN, m_sv_UESUp, m_sv_UESDown;
  float npv, jpt_1,mjj, mjjWoNoisyJets, jeta_1, jeta_2, jpt_2, jphi_1, jphi_2;
  float q_1,q_2;
  float met, metphi, met_px, met_py;
  float bpt_1, beta_1, bphi_1, bflavor_1, bpt_2, beta_2, bphi_2, bflavor_2;
  float againstElectronVLooseMVA6_2,againstElectronLooseMVA6_2,againstElectronMediumMVA6_2,againstElectronTightMVA6_2,againstElectronVTightMVA6_2;
  float againstMuonLoose3_2,againstMuonTight3_2;
  float byVVLooseIsolationMVArun2v2DBoldDMwLT_2, byVLooseIsolationMVArun2v2DBoldDMwLT_2, byLooseIsolationMVArun2v2DBoldDMwLT_2, byMediumIsolationMVArun2v2DBoldDMwLT_2, byTightIsolationMVArun2v2DBoldDMwLT_2, byVTightIsolationMVArun2v2DBoldDMwLT_2, byVVTightIsolationMVArun2v2DBoldDMwLT_2;
  float l2_decayMode;
  float decayModeFinding_2;
  float puweight;
  float npu;
  int NUP;

